# Site settings
title: Tyler Miller | iOS Developer
email: thetylermiller4@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 A site to display some of my work and share some thoughts!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://millerapps.github.io" # the base hostname & protocol for your site
destination: _gh_pages
twitter_username: MillerApps
github_username:  MillerApps

# Build settings
markdown: kramdown
permlinks: /:title
