# Site settings
title: Tyler Miller | iOS Developer
email: tyemiller4@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 A site to display some of my work and share some thoughts!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: TylerMiller4793
# github_username:  jekyll

# Build settings
markdown: kramdown
