# Site settings
# The title of the website.
title: Tyler Miller | iOS Developer
# The email address associated with the website.
email: thetylermiller4@gmail.com
# A brief description of the website.
description: > # this means to ignore newlines until "baseurl:"
 &copy;2024, Tyler Miller
# The subpath of the website.
baseurl: "" # the subpath of your site, e.g. /blog/
# The base URL of the website.
url: "https://millerapps.github.io" # the base hostname & protocol for your site
# The destination folder for the generated site.
destination: _gh_pages
# The Twitter username associated with the website.
twitter_username: MillerApps
# The GitHub username associated with the website.
github_username:  MillerApps
# The Mastodon username associated with the website.
mastodon_username: MillerApps

# Build settings
# The markdown engine to use for rendering content.
markdown: kramdown
  parse_block_html: true
# The permalink structure for the generated pages.
permlinks: /:title
